# Generated by Django 5.2.5 on 2025-08-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_app', '0002_alter_cart_options_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('product', 'Product Inquiry'), ('order', 'Order Support'), ('shipping', 'Shipping Question'), ('return', 'Returns & Exchanges'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
